# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/default.xdc

# Block Designs: bd/DMA_ADDER/DMA_ADDER.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER || ORIG_REF_NAME==DMA_ADDER} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_ADDER_0_0/DMA_ADDER_ADDER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_ADDER_0_0 || ORIG_REF_NAME==DMA_ADDER_ADDER_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_ADDER_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_axi_dma_0_0/DMA_ADDER_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_axi_dma_0_0 || ORIG_REF_NAME==DMA_ADDER_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/DMA_ADDER_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_smartconnect_0_0 || ORIG_REF_NAME==DMA_ADDER_smartconnect_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_xlconcat_0_0/DMA_ADDER_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_xlconcat_0_0 || ORIG_REF_NAME==DMA_ADDER_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_xlslice_0_0/DMA_ADDER_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_xlslice_0_0 || ORIG_REF_NAME==DMA_ADDER_xlslice_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_proc_sys_reset_0_0/DMA_ADDER_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_ADDER_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_xbar_0/DMA_ADDER_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_xbar_0 || ORIG_REF_NAME==DMA_ADDER_xbar_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_axi_interconnect_0_0/DMA_ADDER_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_axi_interconnect_0_0 || ORIG_REF_NAME==DMA_ADDER_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_xlconstant_0_0/DMA_ADDER_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_xlconstant_0_0 || ORIG_REF_NAME==DMA_ADDER_xlconstant_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_xlconstant_1_0/DMA_ADDER_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_xlconstant_1_0 || ORIG_REF_NAME==DMA_ADDER_xlconstant_1_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_system_ila_0_0/DMA_ADDER_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_system_ila_0_0 || ORIG_REF_NAME==DMA_ADDER_system_ila_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_debug_bridge_0_0/DMA_ADDER_debug_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_debug_bridge_0_0 || ORIG_REF_NAME==DMA_ADDER_debug_bridge_0_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_ps8_0_axi_periph_0/DMA_ADDER_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_ps8_0_axi_periph_0 || ORIG_REF_NAME==DMA_ADDER_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_auto_pc_0/DMA_ADDER_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_auto_pc_0 || ORIG_REF_NAME==DMA_ADDER_auto_pc_0} -quiet] -quiet

# IP: bd/DMA_ADDER/ip/DMA_ADDER_auto_pc_1/DMA_ADDER_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_ADDER_auto_pc_1 || ORIG_REF_NAME==DMA_ADDER_auto_pc_1} -quiet] -quiet

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/DMA_ADDER_ooc.xdc
