# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/DMA_ADDER_smartconnect_0_0.xci
# IP: The module: 'DMA_ADDER_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/bd_037c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_0/bd_037c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_2/bd_037c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_3/bd_037c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_4/bd_037c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_5/bd_037c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_6/bd_037c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_7/bd_037c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_8/bd_037c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_9/bd_037c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_10/bd_037c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_13/bd_037c_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_14/bd_037c_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_15/bd_037c_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_16/bd_037c_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_20/bd_037c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_26/bd_037c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_2/bd_037c_arsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_3/bd_037c_rsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_4/bd_037c_awsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_5/bd_037c_wsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_6/bd_037c_bsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_10/bd_037c_s01a2s_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_16/bd_037c_s02a2s_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_20/bd_037c_m00s2a_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/DMA_ADDER_smartconnect_0_0.xci
# IP: The module: 'DMA_ADDER_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/bd_037c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_0/bd_037c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_2/bd_037c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_3/bd_037c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_4/bd_037c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_5/bd_037c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_6/bd_037c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_7/bd_037c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_8/bd_037c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_9/bd_037c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_10/bd_037c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_13/bd_037c_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_14/bd_037c_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_15/bd_037c_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_16/bd_037c_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_20/bd_037c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_26/bd_037c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_1/bd_037c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_2/bd_037c_arsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_3/bd_037c_rsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_4/bd_037c_awsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_5/bd_037c_wsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_6/bd_037c_bsw_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_10/bd_037c_s01a2s_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_11/bd_037c_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_12/bd_037c_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_16/bd_037c_s02a2s_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_17/bd_037c_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_18/bd_037c_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_19/bd_037c_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_20/bd_037c_m00s2a_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_21/bd_037c_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_22/bd_037c_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_23/bd_037c_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_24/bd_037c_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0_ooc.xdc

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/bd_0/ip/ip_25/bd_037c_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
