# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.runs/synth_1/DMA_LED_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_param power.BramSDPPropagationFix 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 12
set_param power.enableLutRouteBelPower 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {17-179}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.cache/wt [current_project]
set_property parent.project_path /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kr260_som:part0:1.1 [current_project]
set_property board_connections {som240_1_connector xilinx.com:kr260_carrier:som240_1_connector:1.1} [current_project]
set_property ip_repo_paths {
  /nas/ei/home/ge43set/ip_repo/LEDAdderIP_1_0
  /nas/ei/home/ge43set/ip_repo/LEDAdderDMA_1_0
  /nas/ei/home/ge43set/ip_repo/LEDAccumulator_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/hdl/DMA_LED_wrapper.v
add_files /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.srcs/sources_1/bd/DMA_LED/DMA_LED.bd
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xbar_0/DMA_LED_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/DMA_LED_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.srcs/constrs_1/new/default.xdc
set_property used_in_implementation false [get_files /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.srcs/constrs_1/new/default.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top DMA_LED_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DMA_LED_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file DMA_LED_wrapper_utilization_synth.rpt -pb DMA_LED_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
