# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/default.xdc

# Block Designs: bd/DMA_LED/DMA_LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED || ORIG_REF_NAME==DMA_LED} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_xlconcat_0_0/DMA_LED_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconcat_0_0 || ORIG_REF_NAME==DMA_LED_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/DMA_LED_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_smartconnect_0_0 || ORIG_REF_NAME==DMA_LED_smartconnect_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_xbar_0/DMA_LED_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xbar_0 || ORIG_REF_NAME==DMA_LED_xbar_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_axi_interconnect_0_0/DMA_LED_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_interconnect_0_0 || ORIG_REF_NAME==DMA_LED_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_xlconstant_0_0/DMA_LED_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_0_0 || ORIG_REF_NAME==DMA_LED_xlconstant_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_xlconstant_1_0/DMA_LED_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_1_0 || ORIG_REF_NAME==DMA_LED_xlconstant_1_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_LEDAdderIP_0_0/DMA_LED_LEDAdderIP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_LEDAdderIP_0_0 || ORIG_REF_NAME==DMA_LED_LEDAdderIP_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_xlslice_0_0/DMA_LED_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlslice_0_0 || ORIG_REF_NAME==DMA_LED_xlslice_0_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_0 || ORIG_REF_NAME==DMA_LED_auto_pc_0} -quiet] -quiet

# IP: bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_1 || ORIG_REF_NAME==DMA_LED_auto_pc_1} -quiet] -quiet

# XDC: /nas/ei/home/ge43set/PS-PL-DMA-LED-URAM/PS-PL-DMA-LED-URAM.gen/sources_1/bd/DMA_LED/DMA_LED_ooc.xdc
