# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'DMA_ADDER_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'DMA_ADDER_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/DMA_ADDER/ip/DMA_ADDER_zynq_ultra_ps_e_0_0/DMA_ADDER_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_ADDER_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
