# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
# IP: The module: 'design_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/coppholl/TB_DMA/TB_DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
# IP: The module: 'design_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/coppholl/TB_DMA/TB_DMA.gen/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
